name: conduit
description: "A minimal Fedimint wallet"
publish_to: 'none'
version: 0.2.0-alpha

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.10.0
  mobile_scanner: ^7.0.1
  pretty_qr_code: ^3.3.0
  intl: ^0.18.1
  numpad_layout: ^0.0.3
  flutter_animate: ^4.5.2
  http: ^1.3.0
  lottie: ^3.3.1
  flutter_speed_dial: ^7.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  currency_picker: ^2.0.21
  freezed_annotation: ^3.0.0
  uuid: ^4.5.1
  crypto: ^3.0.6
  collection: ^1.19.1
  shimmer: ^3.0.0
  package_info_plus: 8.3.1
  fpdart: ^1.1.0
  overlay_support: ^2.1.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"
