name: conduit
description: "A minimal Fedimint Wallet"
publish_to: "none"
version: 0.1.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.10.0
  mobile_scanner: ^7.0.1
  pretty_qr_code: ^3.3.0
  intl: ^0.18.1
  path_provider: ^2.1.5
  currency_picker: ^2.0.21
  freezed_annotation: ^3.0.0
  overlay_support: ^2.1.0
  local_auth: ^2.3.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"
